### ISSUE TITLE
 error: invalid new-expression of abstract class type ‘keyple::core::service::CardSelectionManagerAdapter’

### ISSUE THREAD

**Issue by Andres1012** [eclipse/keyple-service-cpp-lib#7]
Hello, I get this compilation error:
![Screenshot from 2023-03-21 14-04-23](https://user-images.githubusercontent.com/16720540/226728287-f88ccb1b-5a19-4e3b-9df6-a73c1ed940a4.png)

I use the keyple-cpp-meta repository to fetch this repository and compile.

**Comment by jeanpierrefortune** [comment]
Hi Andres1012,

Thank you for reporting this issue.

The problem is related to a mismatch between the API and its implementation. The API has been updated to reflect the latest developments enabling the export and import of selection scenarios, but the implementation is not quite ready yet.

Our team is actively working on implementing the new solution and we plan to release an update as soon as possible to permanently address this issue.

In the meantime, since these features are not fundamental to the functioning of Keyple in standard usage, I suggest disabling them in the API by commenting out lines 121 and 135 in the file `externals\calypsonet-terminal-reader-cpp-api\src\main\selection\CardSelectionManager.h`.

Please keep us informed if you encounter any further issues.

Best regards,

Jean-Pierre

**Comment by Andres1012** [comment]
Excellent! works fine!
Thank you!
